version: '3'

services:
  redis_db:
    container_name: tweet-redis-db
    command: bash -c "redis-server"
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - ./redis-volume:/data
    networks:
      - mybridge

  tweet-searcher:
    container_name: tweet-searcher
    command: bash -c "stage=dev nodemon --watch src server.js"
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    networks:
      - mybridge

networks:
  mybridge:
